// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Queue.Infrastructure.Persistence;

#nullable disable

namespace Queue.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QueueDbContext))]
    [Migration("20260927210929_AddMobileRole")]
    partial class AddMobileRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Queue.Domain.Entities.AppRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_app_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_app_roles_code");

                    b.ToTable("app_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "Admin",
                            Description = "使用者、角色、服務、櫃台、佇列、系統設定、統計",
                            Name = "系統管理員"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "Manager",
                            Description = "佇列、櫃台、統計、部分設定",
                            Name = "管理者"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "Counter",
                            Description = "叫號、再叫、開始、完成、過號、轉移",
                            Name = "櫃台服務人員"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "Display",
                            Description = "讀取佇列狀態、接收 SignalR 事件",
                            Name = "叫號顯示器"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "Kiosk",
                            Description = "取號、讀取服務",
                            Name = "自助取號設備"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "Mobile",
                            Description = "以 QR Token 查詢自己的票據進度",
                            Name = "手機查詢使用者"
                        });
                });

            modelBuilder.Entity("Queue.Domain.Entities.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CounterId")
                        .HasColumnType("bigint")
                        .HasColumnName("counter_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_login_ip");

                    b.Property<DateTimeOffset?>("LockoutEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_app_users");

                    b.HasIndex("CounterId")
                        .HasDatabaseName("ix_app_users_counter");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ux_app_users_username");

                    b.ToTable("app_users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "系統管理員",
                            Email = "admin@queue.local",
                            FailedLoginCount = 0,
                            IsActive = true,
                            PasswordHash = "210000.prHx6RnMQ/c9Qi6+80IedA==.rCnw2+H1R2dVAL3XUvPXzKBYXhNyo/xsh+aBXWmTBOw=",
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2L,
                            CounterId = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "櫃台服務人員 1",
                            FailedLoginCount = 0,
                            IsActive = true,
                            PasswordHash = "210000.Fe1nLmiqK0P0MqQma/BPeA==.+HLJhyKdsN5whTnM4GSoetT0ZcvWHJJBn3MNusEX6IA=",
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "counter1"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Kiosk 服務",
                            FailedLoginCount = 0,
                            IsActive = true,
                            PasswordHash = "210000.asZbnO3AHduCrzY6mLzToA==.5CGPtI6RSYR1tHob0Sdvzr0hwsU9AFQW/BwPpxn22os=",
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserName = "kiosk"
                        });
                });

            modelBuilder.Entity("Queue.Domain.Entities.AppUserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_app_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_app_user_roles_role_id");

                    b.ToTable("app_user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            RoleId = 1L
                        },
                        new
                        {
                            UserId = 1L,
                            RoleId = 2L
                        },
                        new
                        {
                            UserId = 2L,
                            RoleId = 3L
                        },
                        new
                        {
                            UserId = 3L,
                            RoleId = 5L
                        });
                });

            modelBuilder.Entity("Queue.Domain.Entities.QueueCounter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CurrentTicketId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_ticket_id");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("ServiceCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("service_code");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_queue_counters");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_queue_counters_code");

                    b.HasIndex("CurrentTicketId")
                        .HasDatabaseName("ix_queue_counters_current_ticket_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_queue_counters_service_id");

                    b.HasIndex("IsActive", "Status")
                        .HasDatabaseName("ix_queue_counters_status");

                    b.ToTable("queue_counters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "1",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "1 號櫃台",
                            ServiceCode = "GENERAL",
                            ServiceId = 1L,
                            Status = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Weight = 1
                        },
                        new
                        {
                            Id = 2L,
                            Code = "2",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "2 號櫃台",
                            ServiceCode = "VIP",
                            ServiceId = 2L,
                            Status = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Weight = 1
                        },
                        new
                        {
                            Id = 3L,
                            Code = "3",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "3 號櫃台",
                            ServiceCode = "APPOINTMENT",
                            ServiceId = 3L,
                            Status = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Weight = 1
                        },
                        new
                        {
                            Id = 4L,
                            Code = "4",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "4 號櫃台（VIP）",
                            ServiceCode = "VIP",
                            ServiceId = 2L,
                            Status = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Weight = 1
                        },
                        new
                        {
                            Id = 5L,
                            Code = "5",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "5 號櫃台（預約）",
                            ServiceCode = "APPOINTMENT",
                            ServiceId = 3L,
                            Status = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Weight = 1
                        });
                });

            modelBuilder.Entity("Queue.Domain.Entities.QueueDailySequence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CurrentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_number");

                    b.Property<int>("NumberLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("number_length");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("prefix");

                    b.Property<DateOnly>("QueueDate")
                        .HasColumnType("date")
                        .HasColumnName("queue_date");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_queue_daily_sequences");

                    b.HasIndex("QueueDate", "ServiceId")
                        .IsUnique()
                        .HasDatabaseName("ux_queue_daily_sequence_date_service");

                    b.ToTable("queue_daily_sequences", (string)null);
                });

            modelBuilder.Entity("Queue.Domain.Entities.QueueService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<int>("EstimatedServiceMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("estimated_service_minutes");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("NumberLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("number_length");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("prefix");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<bool>("SkipLineEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("skip_line_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_queue_services");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_queue_services_code");

                    b.HasIndex("Prefix")
                        .IsUnique()
                        .HasDatabaseName("ux_queue_services_prefix");

                    b.HasIndex("IsActive", "DisplayOrder")
                        .HasDatabaseName("ix_queue_services_active");

                    b.ToTable("queue_services", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "GENERAL",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "一般業務辦理",
                            DisplayOrder = 1,
                            EstimatedServiceMinutes = 5,
                            IsActive = true,
                            Name = "一般服務",
                            NumberLength = 3,
                            Prefix = "A",
                            Priority = 0,
                            SkipLineEnabled = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2L,
                            Code = "VIP",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "VIP 貴賓專屬服務，優先叫號",
                            DisplayOrder = 2,
                            EstimatedServiceMinutes = 10,
                            IsActive = true,
                            Name = "VIP 服務",
                            NumberLength = 3,
                            Prefix = "V",
                            Priority = 100,
                            SkipLineEnabled = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3L,
                            Code = "APPOINTMENT",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "已預約客戶報到專用",
                            DisplayOrder = 3,
                            EstimatedServiceMinutes = 8,
                            IsActive = true,
                            Name = "預約報到",
                            NumberLength = 3,
                            Prefix = "R",
                            Priority = 50,
                            SkipLineEnabled = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4L,
                            Code = "EXPRESS",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "急件/插單服務",
                            DisplayOrder = 4,
                            EstimatedServiceMinutes = 3,
                            IsActive = true,
                            Name = "急件處理",
                            NumberLength = 3,
                            Prefix = "E",
                            Priority = 200,
                            SkipLineEnabled = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Queue.Domain.Entities.QueueSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("value_type");

                    b.HasKey("Id")
                        .HasName("pk_queue_settings");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_queue_settings_key");

                    b.ToTable("queue_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Queue",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "營業時間（每日重新編號起訖）",
                            IsSystem = true,
                            Key = "queue.business_hours",
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "08:00-17:00",
                            ValueType = "string"
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Queue",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "叫號後等待逾時秒數",
                            IsSystem = true,
                            Key = "queue.recall_timeout_seconds",
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "180",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Queue",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "同一票據最大再叫次數，超過自動過號",
                            IsSystem = true,
                            Key = "queue.max_recall_count",
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "2",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Queue",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "全站平均服務分鐘數（預估等待時間）",
                            IsSystem = true,
                            Key = "queue.average_service_minutes",
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "5",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Queue",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "是否啟用等待老化優先權加成（§17.2）",
                            IsSystem = true,
                            Key = "queue.aging_enabled",
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "false",
                            ValueType = "bool"
                        },
                        new
                        {
                            Id = 6L,
                            Category = "Queue",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "等待老化因子：每 N 分鐘 +1 優先權",
                            IsSystem = true,
                            Key = "queue.aging_factor",
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "10",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 7L,
                            Category = "Display",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "叫號語音播放",
                            IsSystem = true,
                            Key = "display.voice_enabled",
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "true",
                            ValueType = "bool"
                        },
                        new
                        {
                            Id = 8L,
                            Category = "Display",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "語音語言（Web Speech API）",
                            IsSystem = true,
                            Key = "display.voice_language",
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "zh-TW",
                            ValueType = "string"
                        },
                        new
                        {
                            Id = 9L,
                            Category = "Display",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "廣告輪播間隔秒數",
                            IsSystem = true,
                            Key = "display.rotation_seconds",
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "10",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 10L,
                            Category = "Display",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "顯示器廣告輪播內容（以 ｜ 分隔）",
                            IsSystem = true,
                            Key = "display.ads",
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "歡迎光臨服務大廳｜請留意叫號資訊",
                            ValueType = "string"
                        },
                        new
                        {
                            Id = 11L,
                            Category = "Security",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "QR Code Token 有效小時數",
                            IsSystem = true,
                            Key = "security.qr_token_lifetime_hours",
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "72",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 12L,
                            Category = "Kiosk",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kiosk 取號畫面自動重置秒數",
                            IsSystem = true,
                            Key = "kiosk.auto_refresh_seconds",
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "10",
                            ValueType = "int"
                        });
                });

            modelBuilder.Entity("Queue.Domain.Entities.QueueTicket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CallCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("call_count");

                    b.Property<DateTimeOffset?>("CalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("called_at");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long?>("CounterId")
                        .HasColumnType("bigint")
                        .HasColumnName("counter_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_phone");

                    b.Property<DateTimeOffset?>("NoShowAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("no_show_at");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("prefix");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<string>("QrTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("qr_token_hash");

                    b.Property<DateOnly>("QueueDate")
                        .HasColumnType("date")
                        .HasColumnName("queue_date");

                    b.Property<long>("QueuePosition")
                        .HasColumnType("bigint")
                        .HasColumnName("queue_position");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("remark");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_no");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<DateTimeOffset?>("ServingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("serving_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TicketNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticket_no");

                    b.HasKey("Id")
                        .HasName("pk_queue_tickets");

                    b.HasIndex("CounterId", "Status")
                        .HasDatabaseName("ix_queue_ticket_counter_status");

                    b.HasIndex("QueueDate", "Status")
                        .HasDatabaseName("ix_queue_ticket_date_status");

                    b.HasIndex("ServiceId", "Status")
                        .HasDatabaseName("ix_queue_ticket_service_status");

                    b.HasIndex("QueueDate", "Prefix", "SequenceNo")
                        .IsUnique()
                        .HasDatabaseName("ux_queue_ticket_date_prefix_sequence");

                    b.ToTable("queue_tickets", (string)null);
                });

            modelBuilder.Entity("Queue.Domain.Entities.QueueTicketHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<long?>("CounterId")
                        .HasColumnType("bigint")
                        .HasColumnName("counter_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("integer")
                        .HasColumnName("from_status");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("OperatorId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operator_id");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operator_name");

                    b.Property<string>("Remark")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("remark");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint")
                        .HasColumnName("ticket_id");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer")
                        .HasColumnName("to_status");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_queue_ticket_histories");

                    b.HasIndex("Action", "CreatedAt")
                        .HasDatabaseName("ix_queue_history_action");

                    b.HasIndex("TicketId", "Id")
                        .HasDatabaseName("ix_queue_history_ticket");

                    b.ToTable("queue_ticket_histories", (string)null);
                });

            modelBuilder.Entity("Queue.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("Queue.Domain.Entities.QueueCounter", "Counter")
                        .WithMany()
                        .HasForeignKey("CounterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_app_users_counters_counter_id");

                    b.Navigation("Counter");
                });

            modelBuilder.Entity("Queue.Domain.Entities.AppUserRole", b =>
                {
                    b.HasOne("Queue.Domain.Entities.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_user_roles_app_roles_role_id");

                    b.HasOne("Queue.Domain.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_user_roles_app_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Queue.Domain.Entities.QueueCounter", b =>
                {
                    b.HasOne("Queue.Domain.Entities.QueueTicket", "CurrentTicket")
                        .WithMany()
                        .HasForeignKey("CurrentTicketId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_queue_counters_tickets_current_ticket_id");

                    b.HasOne("Queue.Domain.Entities.QueueService", "Service")
                        .WithMany("Counters")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_queue_counters_services_service_id");

                    b.Navigation("CurrentTicket");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Queue.Domain.Entities.QueueTicket", b =>
                {
                    b.HasOne("Queue.Domain.Entities.QueueCounter", "Counter")
                        .WithMany()
                        .HasForeignKey("CounterId")
                        .HasConstraintName("fk_queue_tickets_queue_counters_counter_id");

                    b.HasOne("Queue.Domain.Entities.QueueService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_queue_tickets_queue_services_service_id");

                    b.Navigation("Counter");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Queue.Domain.Entities.QueueTicketHistory", b =>
                {
                    b.HasOne("Queue.Domain.Entities.QueueTicket", "Ticket")
                        .WithMany("Histories")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_queue_ticket_histories_queue_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Queue.Domain.Entities.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Queue.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Queue.Domain.Entities.QueueService", b =>
                {
                    b.Navigation("Counters");
                });

            modelBuilder.Entity("Queue.Domain.Entities.QueueTicket", b =>
                {
                    b.Navigation("Histories");
                });
#pragma warning restore 612, 618
        }
    }
}
